#!/bin/bash

# Copyright (C) 2019 The Android Open Source Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# launcher script for mts-tradefed harness
# can be used from an Android build environment, or a standalone mts zip

UTILS_SCRIPT="$(dirname $(realpath $0))/test-utils-script"

if [ ! -f "${UTILS_SCRIPT}" ]
then
  UTILS_SCRIPT="${ANDROID_BUILD_TOP}/platform_testing/scripts/test-utils-script"
fi

if [ ! -f "${UTILS_SCRIPT}" ]
then
  echo -e "Cannot find test-utils-script in the same location as this script and ANDROID_BUILD_TOP is not defined."
  exit 1
fi

source ${UTILS_SCRIPT}

checkPath adb
checkPath java
checkJavaVersion java

RDBG_FLAG=$(getRemoteDbgFlag)

# get OS
HOST=`uname`
if [ "$HOST" == "Linux" ]; then
    OS="linux-x86"
elif [ "$HOST" == "Darwin" ]; then
    OS="darwin-x86"
else
    echo "Unrecognized OS"
    exit
fi

# check if in Android build env
if [ ! -z "${ANDROID_BUILD_TOP}" ]; then
    if [ ! -z "${ANDROID_HOST_OUT}" ]; then
      MTS_ROOT=${ANDROID_HOST_OUT}/mts
    else
      MTS_ROOT=${ANDROID_BUILD_TOP}/${OUT_DIR:-out}/host/${OS}/mts
    fi
    if [ ! -d ${MTS_ROOT} ]; then
        echo "Could not find $MTS_ROOT in Android build environment. Try 'make mts'"
        exit
    fi;
fi;

if [ -z ${MTS_ROOT} ]; then
    # assume we're in an extracted mts install
    MTS_ROOT="$(dirname $0)/../.."
fi;

JAR_DIR=${MTS_ROOT}/android-mts/tools

for JAR in ${JAR_DIR}/*.jar; do
    JAR_PATH=${JAR_PATH}:${JAR}
done

# check if APE_API_KEY is set in the env by user.
if [ ! -n "${APE_API_KEY}" ]; then
    GTS_GOOGLE_SERVICE_ACCOUNT=${ANDROID_BUILD_TOP}/vendor/xts/tools/gts-google-service-account/gts-google-service-account.json
    # set KEY only for google if APE_API_KEY isn't set and GTS_GOOGLE_SERVICE_ACCOUNT exists in the soure tree.
    if [ -f "$GTS_GOOGLE_SERVICE_ACCOUNT" ]; then
        APE_API_KEY=${GTS_GOOGLE_SERVICE_ACCOUNT}
        export APE_API_KEY
    else
        echo "APE_API_KEY not set, GTS tests may fail without authentication."
    fi;
fi;
echo "APE_API_KEY: $APE_API_KEY"

LIB_DIR=${MTS_ROOT}/android-mts/lib
loadSharedLibraries "$HOST" "$LIB_DIR"

# include any host-side test jars
for j in $(find ${MTS_ROOT}/android-mts/testcases -name '*.jar'); do
    JAR_PATH=${JAR_PATH}:$j
done

java $RDBG_FLAG -cp ${JAR_PATH} -DMTS_ROOT=${MTS_ROOT} com.android.compatibility.common.tradefed.command.CompatibilityConsole "$@"


